Contributed Project Fuse source code
edgexfoundry/ci-management pull request #2
Opened 2017-05-25 15:19 UTC by trcox

Signed-off-by: Tyler Cox <tyler_cox@dell.com>

2017-05-25 16:16 UTC, tykeal commented on jobs/java-maven-template.yaml
> +    project-type: maven
We do not allow 'project-type: maven' in our build environment. The templates must use a freestyle type.

2017-05-25 16:17 UTC, tykeal commented on jenkins_jobs.ini
> +[jenkins]
This entire file needs to go away. We provide an example jenkins.ini file and our .gitignore is configure to ignore jenkins.ini files themselves as they hold credentials.

2017-05-25 16:18 UTC, tykeal commented on jobs/global-defaults.yaml
> +- defaults:
We already provide a defaults file and his one runs afoul of several problems we've generally worked around

2017-05-25 16:33 UTC, tykeal requested changes
Hmm... I started going through this and marking things up but realized that there's a lot wrong with it.

First you have files that hold credentials. We never post do this, you're going to have to do a squash commit to your PR to get rid of them as well as remove them from the history. Besides, none of those credentials are valid in our environment.

Second, all the job definitions are in jobs directory instead of the JJB directory that is already part of the project. We only pull job definitions out of that directory

Third, all of these jobs are pointing at the bitbucket repositories.

Fourth, I don't see any verify / merge job distinctions here. Pretty much all of the jobs presently don't hold with our standard ideas of how the code flow should work:

PR triggers a verification job
Merge triggers a merge job which produces artifacts

Fifth, the jobs are all defined in one file / location and not broken up a more granular fashion. We generally recommend that projects (or specific project groups) use the following structure for their jobs:

jjb/<project>/<project>.yaml
jjb/<project>/<project-additions>.yaml

Given the number of problems I'm seeing I'll see if I can work up something that is more in line with our normal flows. Going off in a direction that is significantly different from our other supported projects makes it very hard for the LF Release Engineering team to support the jobs.

2017-05-31 20:23 UTC, JPWKU commented
recheck

2017-05-31 20:25 UTC, JPWKU commented
recheck

2017-05-31 20:26 UTC, JPWKU commented
recheck

2017-06-21 15:18 UTC, closed without merging