Adding a base docker image for builds using gcc
edgexfoundry/ci-management pull request #274
Opened 2019-01-25 18:40 UTC by lranjbar

Similar to the go base image that @ernestojeda made. Goal is to have a bare bones image for the gcc tool chain.

Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

2019-01-28 18:26 UTC, jamesrgregg commented
@lranjbar when I was testing the build of device-sdk-c I also needed these additional dependencies
wget libcurl 
Can we add them as well?

2019-01-30 17:45 UTC, lranjbar commented
@jamesrgregg @MightyNerdEric I'm still testing these changes on sandbox this was more to test out squashing commits.

2019-02-08 23:06 UTC, lranjbar commented
Dependency on #282

2019-02-12 15:09 UTC, ernestojeda reviewed
I am not sure I follow why all these custom triggers are needed now. I think I may be missing some context. I thought the goal was to remove any reverse triggers for '{project-name}-{stream}-merge-java' except in the case of the `support-rulesengine.yaml` template. Why is it needed in so many non-java projects like `edgex-mongo.yaml` or `core-consul.yaml`

2019-02-12 15:11 UTC, ernestojeda commented on jjb/core/core-consul.yaml
> +                jobs: '{project-name}-{stream}-merge-java'
See my review comment for context. Not following why this is needed, I thought we were removing merge-java references.

2019-02-12 15:12 UTC, ernestojeda commented on jjb/ci-management/docker.yaml
> +            - github
Is this a new trigger? Should we be adding this to other docker templates.

2019-02-15 23:39 UTC, lranjbar commented
@ernestojeda @JPWKU @jamesrgregg 

Just rebased this change and it should be good to go now with the other PRs resolved.

2019-02-15 23:45 UTC, eb-oss approved these changes

2019-02-16 00:01 UTC, eb-oss requested changes
Please change commit message to be imperative ("Add a base docker image...").

2019-02-19 17:03 UTC, jamesrgregg approved these changes
LGTM - thanks for fixing the commit message

2019-02-19 17:22 UTC, eb-oss approved these changes

2019-02-19 17:22 UTC, merged