Added verify job files for the new Go module repos.
edgexfoundry/ci-management pull request #283
Opened 2019-02-11 15:58 UTC by lenny-intel

2019-02-11 17:40 UTC, tsconn23 requested changes

2019-02-11 17:40 UTC, tsconn23 commented on jjb/go-modules/go-mod-contracts.yaml
> +    name: go-mod-contracts
Would recommend all of the references to `go-mod-contracts` be changed to `go-mod-core-contracts` to match the repo name.

2019-02-12 00:00 UTC, eb-oss submitted a review, later dismissed
LGTM. I'm approving, but I'll wait for @tsconn23 to update his comments and see if he'd like any other changes before I merge.

2019-02-12 22:24 UTC, tsconn23 submitted a review, later dismissed

2019-02-13 01:35 UTC, tsconn23 commented
recheck

2019-02-13 02:00 UTC, tsconn23 approved these changes

2019-02-13 02:00 UTC, merged