remove make prepare as the default pre-build script
edgexfoundry/ci-management pull request #351
Opened 2019-04-22 23:21 UTC by ernestojeda

2019-04-22 23:26 UTC, ernestojeda commented
I am removing the default pre-build script of `make prepare && make test` for all builds. I am allowing the california and delhi builds to revert to the previous pre-build script and all new builds should install a specific Go version and run `make test && make build docker`. This goes along with https://github.com/edgexfoundry/edgex-go/pull/1277

2019-04-22 23:47 UTC, jamesrgregg requested changes
please address the DCO signoff

2019-04-23 00:13 UTC, ernestojeda commented
> please address the DCO signoff

Thanks for catching that. I pushed a another commit.

2019-04-23 01:45 UTC, jamesrgregg approved these changes

2019-04-23 01:45 UTC, merged