removing images after migration to ci-build-images
edgexfoundry/ci-management pull request #360
Opened 2019-05-06 16:31 UTC by ernestojeda

After migrating the Go and GCC base docker images over to: https://github.com/edgexfoundry/ci-build-images, the corresponding builds here in ci-management are redundant. This PR removes the no longer used docker builds.

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

2019-05-06 16:41 UTC, ernestojeda commented
The Docker verify checks will fail since we are removing the files. Maybe I will have to do this in two separate PR's. The first PR would only remove the JJB templates. The second PR would remove the Dockerfiles.

2019-05-06 16:43 UTC, lranjbar submitted a review, later dismissed
LGTM. 

I looked at the errors in the logs. It's failing because it can't build the images after the removal of the Dockerfiles. Should be fine because this also removes the failing jobs.

2019-05-06 18:17 UTC, eb-oss requested changes
Please change commit message to imperative form.

2019-05-07 00:31 UTC, eb-oss approved these changes

2019-05-07 00:32 UTC, merged