Add daily java and docker release jobs
edgexfoundry/ci-management pull request #42
Opened 2017-09-22 19:31 UTC by JPWKU

These jobs run daily and push artifacts to the
Nexus staging repository.

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

2017-09-22 19:44 UTC, trcox requested changes
Need daily job definitions for the support/* jobs

2017-09-22 19:48 UTC, JPWKU commented
@trcox Updated to include support/* jobs

2017-09-22 19:49 UTC, trcox approved these changes
LGTM

2017-09-22 22:29 UTC, JPWKU commented on jjb/edgex-templates-docker.yaml
> +    triggers:
@tykeal I missed this

2017-09-22 22:30 UTC, JPWKU commented on jjb/edgex-templates-docker.yaml
> +    triggers:
It was scoped inside the builder section

2017-09-25 20:06 UTC, tykeal approved these changes

2017-09-25 20:07 UTC, merged