[DRAFT] Add Golang JJB templates
edgexfoundry/ci-management pull request #70
Opened 2017-12-06 20:03 UTC by JPWKU

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

2017-12-06 21:23 UTC, trcox submitted a review, later dismissed

2017-12-06 22:17 UTC, jpwhitemn approved these changes

2017-12-06 22:20 UTC, JPWKU commented
@trcox @jpwhitemn I am thinking of doing a top level Makefile.  Will the present a problem for Windows users when building go services?

2017-12-08 20:24 UTC, tykeal requested changes
Please break out the shell scripts into includes so that ShellCheck can run across them

2017-12-08 20:24 UTC, tykeal commented on jjb/edgex-templates-go.yaml
> +      - shell: |
Shell scripts should be done as includes and not inlined

2017-12-08 20:24 UTC, tykeal commented on jjb/edgex-templates-go.yaml
> +      - shell: |
Shell scripts should be done as includes and not inlined

2017-12-08 20:24 UTC, tykeal commented on jjb/edgex-templates-go.yaml
> +      - shell: |
Shell scripts should be done as includes and not inlined

2017-12-08 20:24 UTC, tykeal commented on jjb/edgex-templates-go.yaml
> +      - shell: |
Shell scripts should be done as includes and not inlined

2018-02-07 13:55 UTC, JPWKU commented
@tykeal the build commands will be contained in Makefile and driven that way.  I'd like to go ahead and get this merged so we can incrementally build it out.

2018-02-07 16:46 UTC, tykeal approved these changes

2018-02-07 16:47 UTC, merged