Adding initial verify and merge templates
edgexfoundry/ci-management pull request #8
Opened 2017-06-14 20:19 UTC by tykeal

Add the initial verify and merge templates for java projects

Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>

2017-06-14 20:39 UTC, tykeal commented
@jpwhitemn and @trcox Here's my initial foray into the verify and merge templates for Java projects.

2017-06-14 20:53 UTC, JPWKU commented on jjb/edgex-templates-java.yaml
> +
No triggers for merge job?

2017-06-14 21:05 UTC, tykeal commented on jjb/edgex-templates-java.yaml
> +
Hmm... good catch. I just pushed a new version of it. I'm rather disliking the lost change history here :-/

2017-06-15 13:12 UTC, JPWKU commented
LGTM so far but wanna get @zxiiro to look at it too.

2017-06-15 18:36 UTC, zxiiro requested changes
Mainly about `clean deploy`. Fix that and the rest looks good.

2017-06-15 18:36 UTC, zxiiro commented on jjb/edgex-templates-java.yaml
> +    mvn-goals: 'clean install deploy'
clean deploy

"install" is part of the deploy goal so it's redundant.

2017-06-15 18:36 UTC, zxiiro commented on jjb/edgex-templates-java.yaml
> +            - deployAtEnd=true
Keep in mind that if any poms in hte project sets <extensions>true</extensions> this breaks.

2017-06-15 18:44 UTC, tykeal commented on jjb/edgex-templates-java.yaml
> +    mvn-goals: 'clean install deploy'
Fixed

2017-06-15 18:44 UTC, tykeal commented on jjb/edgex-templates-java.yaml
> +            - deployAtEnd=true
None of the projects do currently

2017-06-15 18:46 UTC, zxiiro approved these changes

2017-06-15 18:46 UTC, merged